
---

version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: node:6.10-alpine
    environment:
      - GHR_VERSION: "v0.5.4"
    steps:
      - run:
          name: install-ependencies
          command: |
            apk add --no-cache zip curl git
            curl -OL https://github.com/tcnksm/ghr/releases/download/$GHR_VERSION/ghr_"$GHR_VERSION"_linux_amd64.zip
            unzip ghr_"$GHR_VERSION"_linux_amd64.zip
            mv ghr /usr/bin/
            rm -f "ghr_"$GHR_VERSION"_linux_amd64.zip"
      - checkout
      - run:
          name: update-npm
          command: npm install
      - run:
          name: package
          command: zip -r deploy-function.zip index.js src node_modules
      - run:
          name: release
          command: ghr v0.0.1 deploy-function.zip

